sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=javalite480
    - REGISTRY_PASS=@prilF00l
    - secret: "<something long>"

script:
  - docker build --tag myorg/myimage .
  - docker run myorg/myimage

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push myorg/myimage
  on:
    branch: master
